// flow-typed signature: 35d35eb12aa040632c3598df65d94bd4
// flow-typed version: <<STUB>>/react-css-transition_v^0.7.4/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-css-transition'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-css-transition' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-css-transition/cjs/composables/mergeWithBaseStyle' {
  declare module.exports: any;
}

declare module 'react-css-transition/cjs/composables/preventPhantomEvents' {
  declare module.exports: any;
}

declare module 'react-css-transition/cjs/composables/withDOMNodeCallback' {
  declare module.exports: any;
}

declare module 'react-css-transition/cjs/composables/withTimeout' {
  declare module.exports: any;
}

declare module 'react-css-transition/cjs/composables/withTransitionInfo' {
  declare module.exports: any;
}

declare module 'react-css-transition/cjs/composables/withTransitionObserver' {
  declare module.exports: any;
}

declare module 'react-css-transition/cjs/composables/withTransitionState' {
  declare module.exports: any;
}

declare module 'react-css-transition/cjs/composables/withWorkaround' {
  declare module.exports: any;
}

declare module 'react-css-transition/cjs/csstransition' {
  declare module.exports: any;
}

declare module 'react-css-transition/cjs/csstransitiongroup' {
  declare module.exports: any;
}

declare module 'react-css-transition/cjs/index' {
  declare module.exports: any;
}

declare module 'react-css-transition/cjs/reducer' {
  declare module.exports: any;
}

declare module 'react-css-transition/cjs/transit' {
  declare module.exports: any;
}

declare module 'react-css-transition/cjs/utils/convertToCSSPrefix' {
  declare module.exports: any;
}

declare module 'react-css-transition/cjs/utils/matchTransitionProperty' {
  declare module.exports: any;
}

declare module 'react-css-transition/cjs/utils/memoize' {
  declare module.exports: any;
}

declare module 'react-css-transition/cjs/utils/parseComputedTransition' {
  declare module.exports: any;
}

declare module 'react-css-transition/cjs/utils/parseDuration' {
  declare module.exports: any;
}

declare module 'react-css-transition/cjs/utils/parseTransition' {
  declare module.exports: any;
}

declare module 'react-css-transition/cjs/utils/pick' {
  declare module.exports: any;
}

declare module 'react-css-transition/cjs/utils/removeVendorPrefix' {
  declare module.exports: any;
}

declare module 'react-css-transition/cjs/utils/runInFrame' {
  declare module.exports: any;
}

declare module 'react-css-transition/cjs/utils/shallowEqual' {
  declare module.exports: any;
}

declare module 'react-css-transition/dist/react-css-transition' {
  declare module.exports: any;
}

declare module 'react-css-transition/dist/react-css-transition.min' {
  declare module.exports: any;
}

declare module 'react-css-transition/lib/composables/mergeWithBaseStyle' {
  declare module.exports: any;
}

declare module 'react-css-transition/lib/composables/preventPhantomEvents' {
  declare module.exports: any;
}

declare module 'react-css-transition/lib/composables/withDOMNodeCallback' {
  declare module.exports: any;
}

declare module 'react-css-transition/lib/composables/withTimeout' {
  declare module.exports: any;
}

declare module 'react-css-transition/lib/composables/withTransitionInfo' {
  declare module.exports: any;
}

declare module 'react-css-transition/lib/composables/withTransitionObserver' {
  declare module.exports: any;
}

declare module 'react-css-transition/lib/composables/withTransitionState' {
  declare module.exports: any;
}

declare module 'react-css-transition/lib/composables/withWorkaround' {
  declare module.exports: any;
}

declare module 'react-css-transition/lib/csstransition' {
  declare module.exports: any;
}

declare module 'react-css-transition/lib/csstransitiongroup' {
  declare module.exports: any;
}

declare module 'react-css-transition/lib/index' {
  declare module.exports: any;
}

declare module 'react-css-transition/lib/reducer' {
  declare module.exports: any;
}

declare module 'react-css-transition/lib/transit' {
  declare module.exports: any;
}

declare module 'react-css-transition/lib/utils/convertToCSSPrefix' {
  declare module.exports: any;
}

declare module 'react-css-transition/lib/utils/matchTransitionProperty' {
  declare module.exports: any;
}

declare module 'react-css-transition/lib/utils/memoize' {
  declare module.exports: any;
}

declare module 'react-css-transition/lib/utils/parseComputedTransition' {
  declare module.exports: any;
}

declare module 'react-css-transition/lib/utils/parseDuration' {
  declare module.exports: any;
}

declare module 'react-css-transition/lib/utils/parseTransition' {
  declare module.exports: any;
}

declare module 'react-css-transition/lib/utils/pick' {
  declare module.exports: any;
}

declare module 'react-css-transition/lib/utils/removeVendorPrefix' {
  declare module.exports: any;
}

declare module 'react-css-transition/lib/utils/runInFrame' {
  declare module.exports: any;
}

declare module 'react-css-transition/lib/utils/shallowEqual' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-css-transition/cjs/composables/mergeWithBaseStyle.js' {
  declare module.exports: $Exports<'react-css-transition/cjs/composables/mergeWithBaseStyle'>;
}
declare module 'react-css-transition/cjs/composables/preventPhantomEvents.js' {
  declare module.exports: $Exports<'react-css-transition/cjs/composables/preventPhantomEvents'>;
}
declare module 'react-css-transition/cjs/composables/withDOMNodeCallback.js' {
  declare module.exports: $Exports<'react-css-transition/cjs/composables/withDOMNodeCallback'>;
}
declare module 'react-css-transition/cjs/composables/withTimeout.js' {
  declare module.exports: $Exports<'react-css-transition/cjs/composables/withTimeout'>;
}
declare module 'react-css-transition/cjs/composables/withTransitionInfo.js' {
  declare module.exports: $Exports<'react-css-transition/cjs/composables/withTransitionInfo'>;
}
declare module 'react-css-transition/cjs/composables/withTransitionObserver.js' {
  declare module.exports: $Exports<'react-css-transition/cjs/composables/withTransitionObserver'>;
}
declare module 'react-css-transition/cjs/composables/withTransitionState.js' {
  declare module.exports: $Exports<'react-css-transition/cjs/composables/withTransitionState'>;
}
declare module 'react-css-transition/cjs/composables/withWorkaround.js' {
  declare module.exports: $Exports<'react-css-transition/cjs/composables/withWorkaround'>;
}
declare module 'react-css-transition/cjs/csstransition.js' {
  declare module.exports: $Exports<'react-css-transition/cjs/csstransition'>;
}
declare module 'react-css-transition/cjs/csstransitiongroup.js' {
  declare module.exports: $Exports<'react-css-transition/cjs/csstransitiongroup'>;
}
declare module 'react-css-transition/cjs/index.js' {
  declare module.exports: $Exports<'react-css-transition/cjs/index'>;
}
declare module 'react-css-transition/cjs/reducer.js' {
  declare module.exports: $Exports<'react-css-transition/cjs/reducer'>;
}
declare module 'react-css-transition/cjs/transit.js' {
  declare module.exports: $Exports<'react-css-transition/cjs/transit'>;
}
declare module 'react-css-transition/cjs/utils/convertToCSSPrefix.js' {
  declare module.exports: $Exports<'react-css-transition/cjs/utils/convertToCSSPrefix'>;
}
declare module 'react-css-transition/cjs/utils/matchTransitionProperty.js' {
  declare module.exports: $Exports<'react-css-transition/cjs/utils/matchTransitionProperty'>;
}
declare module 'react-css-transition/cjs/utils/memoize.js' {
  declare module.exports: $Exports<'react-css-transition/cjs/utils/memoize'>;
}
declare module 'react-css-transition/cjs/utils/parseComputedTransition.js' {
  declare module.exports: $Exports<'react-css-transition/cjs/utils/parseComputedTransition'>;
}
declare module 'react-css-transition/cjs/utils/parseDuration.js' {
  declare module.exports: $Exports<'react-css-transition/cjs/utils/parseDuration'>;
}
declare module 'react-css-transition/cjs/utils/parseTransition.js' {
  declare module.exports: $Exports<'react-css-transition/cjs/utils/parseTransition'>;
}
declare module 'react-css-transition/cjs/utils/pick.js' {
  declare module.exports: $Exports<'react-css-transition/cjs/utils/pick'>;
}
declare module 'react-css-transition/cjs/utils/removeVendorPrefix.js' {
  declare module.exports: $Exports<'react-css-transition/cjs/utils/removeVendorPrefix'>;
}
declare module 'react-css-transition/cjs/utils/runInFrame.js' {
  declare module.exports: $Exports<'react-css-transition/cjs/utils/runInFrame'>;
}
declare module 'react-css-transition/cjs/utils/shallowEqual.js' {
  declare module.exports: $Exports<'react-css-transition/cjs/utils/shallowEqual'>;
}
declare module 'react-css-transition/dist/react-css-transition.js' {
  declare module.exports: $Exports<'react-css-transition/dist/react-css-transition'>;
}
declare module 'react-css-transition/dist/react-css-transition.min.js' {
  declare module.exports: $Exports<'react-css-transition/dist/react-css-transition.min'>;
}
declare module 'react-css-transition/lib/composables/mergeWithBaseStyle.js' {
  declare module.exports: $Exports<'react-css-transition/lib/composables/mergeWithBaseStyle'>;
}
declare module 'react-css-transition/lib/composables/preventPhantomEvents.js' {
  declare module.exports: $Exports<'react-css-transition/lib/composables/preventPhantomEvents'>;
}
declare module 'react-css-transition/lib/composables/withDOMNodeCallback.js' {
  declare module.exports: $Exports<'react-css-transition/lib/composables/withDOMNodeCallback'>;
}
declare module 'react-css-transition/lib/composables/withTimeout.js' {
  declare module.exports: $Exports<'react-css-transition/lib/composables/withTimeout'>;
}
declare module 'react-css-transition/lib/composables/withTransitionInfo.js' {
  declare module.exports: $Exports<'react-css-transition/lib/composables/withTransitionInfo'>;
}
declare module 'react-css-transition/lib/composables/withTransitionObserver.js' {
  declare module.exports: $Exports<'react-css-transition/lib/composables/withTransitionObserver'>;
}
declare module 'react-css-transition/lib/composables/withTransitionState.js' {
  declare module.exports: $Exports<'react-css-transition/lib/composables/withTransitionState'>;
}
declare module 'react-css-transition/lib/composables/withWorkaround.js' {
  declare module.exports: $Exports<'react-css-transition/lib/composables/withWorkaround'>;
}
declare module 'react-css-transition/lib/csstransition.js' {
  declare module.exports: $Exports<'react-css-transition/lib/csstransition'>;
}
declare module 'react-css-transition/lib/csstransitiongroup.js' {
  declare module.exports: $Exports<'react-css-transition/lib/csstransitiongroup'>;
}
declare module 'react-css-transition/lib/index.js' {
  declare module.exports: $Exports<'react-css-transition/lib/index'>;
}
declare module 'react-css-transition/lib/reducer.js' {
  declare module.exports: $Exports<'react-css-transition/lib/reducer'>;
}
declare module 'react-css-transition/lib/transit.js' {
  declare module.exports: $Exports<'react-css-transition/lib/transit'>;
}
declare module 'react-css-transition/lib/utils/convertToCSSPrefix.js' {
  declare module.exports: $Exports<'react-css-transition/lib/utils/convertToCSSPrefix'>;
}
declare module 'react-css-transition/lib/utils/matchTransitionProperty.js' {
  declare module.exports: $Exports<'react-css-transition/lib/utils/matchTransitionProperty'>;
}
declare module 'react-css-transition/lib/utils/memoize.js' {
  declare module.exports: $Exports<'react-css-transition/lib/utils/memoize'>;
}
declare module 'react-css-transition/lib/utils/parseComputedTransition.js' {
  declare module.exports: $Exports<'react-css-transition/lib/utils/parseComputedTransition'>;
}
declare module 'react-css-transition/lib/utils/parseDuration.js' {
  declare module.exports: $Exports<'react-css-transition/lib/utils/parseDuration'>;
}
declare module 'react-css-transition/lib/utils/parseTransition.js' {
  declare module.exports: $Exports<'react-css-transition/lib/utils/parseTransition'>;
}
declare module 'react-css-transition/lib/utils/pick.js' {
  declare module.exports: $Exports<'react-css-transition/lib/utils/pick'>;
}
declare module 'react-css-transition/lib/utils/removeVendorPrefix.js' {
  declare module.exports: $Exports<'react-css-transition/lib/utils/removeVendorPrefix'>;
}
declare module 'react-css-transition/lib/utils/runInFrame.js' {
  declare module.exports: $Exports<'react-css-transition/lib/utils/runInFrame'>;
}
declare module 'react-css-transition/lib/utils/shallowEqual.js' {
  declare module.exports: $Exports<'react-css-transition/lib/utils/shallowEqual'>;
}
